### ISSUE TITLE
Re-routing to non-existing url

### ISSUE THREAD

**Issue by marvinm2** [bridgedb/BridgeDb#69] opened 2018-03-28 15:06 UTC
The rerouting link (http://developers.bridgedb.org/wiki/BridgeWebservice) does not work and should be changed to http://webservice.bridgedb.org/. @JonathanMELIUS already fixed this on his machine.

**Comment by egonw** [comment] 2018-04-09 06:36
Duplicate of #71

**Closed by egonw** 2018-04-09 06:36 UTC
